title: Codebreak Station
email: your-email@example.com
description: >-
  Here I write about some practices in software development
baseurl: ""
url: "https://codebreakstation.com"
github_username: jekyll
bitbucket_username: oooo
linkedin_username: oooo
permalink: /:title

theme: bay_jekyll_theme
plugins:
  - jekyll-feed

header:
  pages:
    - name: About me
      slug: /about
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/YourGitHubUsername
    - name: Bitbucket
      link: http://github.com/YourGitHubUsername
