title: Codebreak Station
email: codebreakstation@gmail.com
description: >-
  Here I write about some practices in software development
baseurl: ""
url: "https://codebreakstation.com"
github_username: jekyll
bitbucket_username: oooo
linkedin_username: oooo
permalink: /:title

plugins:
  - jekyll-feed

header:
  pages:
    - name: About me
      slug: /about
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: codebreakstation@gmail.com
      link: mailto:codebreakstation@gmail.com
