title: Codebreak Station
email: codebreakstation@gmail.com
description: >-
  Personal blog about some practices in software development mainly in Java, Spring, Flutter and some frontend libraries
baseurl: ""
url: "https://codebreakstation.com"
github_username: jekyll
bitbucket_username: oooo
linkedin_username: oooo
permalink: /:title

plugins:
  - jekyll-feed

header:
  pages:
    - name: About
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: codebreakstation@gmail.com
      link: mailto:codebreakstation@gmail.com
  follow:
    - name: Linkedin
      link: https://www.linkedin.com/in/rodrigo-santos-49b23932
    - name: Github
      link: https://github.com/xrodrigo1982x
    - name: Bitbucket
      link: https://bitbucket.org/rodrigo82
